services:
    postgres:
        image: postgres:18.3-alpine
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - postgres_data:/var/lib/postgresql
        networks:
            - data-network
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
            interval: 5s
            retries: 5

    airflow:
        image: apache/airflow:slim-latest
        ports:
            - "8080:8080"
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            AIRFLOW__CORE__LOAD_EXAMPLES: "false"
            AIRFLOW__CORE__EXECUTOR: SequentialExecutor
            AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
            DBT_PROFILES_DIR: /opt/airflow
            DB_HOST: postgres
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            DB_PORT: ${DB_PORT}
            URL: ${URL}
        volumes:
            - ./dags:/opt/airflow/dags
            - ./src:/opt/airflow/src
            - ./electric_vehicles:/opt/airflow/electric_vehicles
            - ./data:/opt/airflow/data
            - ./profiles.yml:/opt/airflow/profiles.yml
            - airflow_home:/opt/airflow
        command: ["bash", "-c", "pip install --quiet pandas psycopg2-binary sqlalchemy python-dotenv dbt-postgres && airflow db migrate && airflow standalone"]
        networks:
            - data-network

    superset:
        build:
            context: .
            dockerfile: Dockerfile.superset
        ports:
            - "8088:8088"
        environment:
            SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
            SUPERSET_ADMIN_USERNAME: ${SUPERSET_ADMIN_USERNAME}
            SUPERSET_ADMIN_FIRSTNAME: ${SUPERSET_ADMIN_FIRSTNAME}
            SUPERSET_ADMIN_LASTNAME: ${SUPERSET_ADMIN_LASTNAME}
            SUPERSET_ADMIN_EMAIL: ${SUPERSET_ADMIN_EMAIL}
            SUPERSET_ADMIN_PASSWORD: ${SUPERSET_ADMIN_PASSWORD}
        volumes:
            - superset_home:/app/superset_home
            - ./superset_config.py:/app/pythonpath/superset_config.py:ro
        command: >
            bash -c "
            superset db upgrade &&
            superset fab create-admin --username ${SUPERSET_ADMIN_USERNAME} --firstname ${SUPERSET_ADMIN_FIRSTNAME} --lastname ${SUPERSET_ADMIN_LASTNAME} --email ${SUPERSET_ADMIN_EMAIL} --password ${SUPERSET_ADMIN_PASSWORD} || true &&
            superset init &&
            superset run -h 0.0.0.0 -p 8088 --with-threads
            "
        networks:
            - data-network

volumes:
    postgres_data:
    superset_home:
    airflow_home:

networks:
    data-network:
