electric_vehicles:
  outputs:
    dev:
      type: postgres
      host: postgres
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: "{{ env_var('DB_PORT') | int }}"
      database: "{{ env_var('POSTGRES_DB') }}"
      schema: public
      threads: 1
  target: dev